### ISSUE TITLE
Integrating networked Boris with swank-php

### ISSUE THREAD

**Issue by steckerhalter** [joddie/boris#2]
So after some work I've got swank-php (https://github.com/steckerhalter/swank-php) to the point where you can connect with SLIME and get a prompt, send stuff back etc.

Now I need to integrate some kind of REPL and I think it would be best to use your networked Boris. So swank-php would send what it got to evaluate from SLIME to Boris over the network, receive an answer and forward that to SLIME again.

This way the components can be maintained separately and Boris can still be used standalone.

For the communication SWANK <-> Boris we need to define a simple protocol that handles the calls the REPL is needed for... 

Are you interested to go forward in this direction?

Cheers

**Comment by steckerhalter** [comment]
btw, I tested your Elisp but couldn't get anything out other than a hanging Emacs yet

**Comment by steckerhalter** [comment]
got the Elisp part to work after some more tries

**Comment by steckerhalter** [comment]
anyway... I just used the protocol you already provide. completions work now in SLIME:

![swank-php](https://f.cloud.github.com/assets/3024024/1012268/c9102d1a-0b6c-11e3-9174-b369acb12fc6.png)

SLIME provides many other neat features and once the protocol works (which is the case now) it's fairly easy to plugin more goodies.

**Comment by joddie** [comment]
Neat! I haven't had a chance to look at your code yet, but it's good to see someone else is interested in building on this.

That said, I am skeptical that the slime/swank protocol is the best way to go for this.  Here are my thoughts, maybe you can convince me I'm wrong. ;-) 

I can think of three projects that used SLIME for something other than Common Lisp or Scheme: swank-clojure, swank-js, and swank-R.  I don't know anything about the last one, but swank-clojure was finally dropped by its developers and replaced with nrepl, which uses its own protocol. And that was for Clojure, which is a lot closer to CL syntactically (and semantically?) than PHP or any of these other languages.  Swank-js is around, but when I tried it seemed like a hassle to set up due to protocol version differences between different versions of the client and server. (You mention ternjs in your readme, what kind of protocol does that use?)

One of the original SLIME hackers, Luke Gorrie, has an interesting 15min talk on it at https://www.youtube.com/watch?v=eZDWJfB9XY4 . Around 14:00 he recommends against using SLIME for other languages and encourages people to write their own language integration instead (tho he likes swank-R).  One example I can think of is that the slime debugger depends heavily on CL's handling of conditions and exceptions, which can't really be duplicated in any other language.

I definitely see not wanting to reinvent the wheel, and it would be _really_ nice if Emacs could settle on a single, good RPC protocol, but I suspect building from scratch -- or on some less-language-specific foundation -- is preferable in this case.  However, I'm open to being convinced otherwise (and you may have more time to hack on this than I have).  What other stuff would we get from slime for free if we went with it?  The stuff I am interested in mostly already works (for me).  It would be nice to have smarter completions, but to get that would require significant static analysis (an interesting project, but I'm not sure if the gains justify the cost).  

It also depends on what @d11wtq wants to do with Boris itself, of course.

**Comment by steckerhalter** [comment]
hey... yeah well, I think the hard part with SLIME in that you need to parse and build s-exps to communicate so that's probably why he recommends against using it for other languages.

You can find a few features of the protocol here: https://github.com/astine/swank-client/blob/master/swank-description.markdown

It has many other builtin goodies as I can see from observing the CL SLIME log. It involves some kind of reverse engineering of course. It has eldoc/autodoc included and help popups worked out the box with your backend. Autodoc though would have to be tweaked a bit because for PHP it sends the wrong part of the string.

I think the benefit is that SLIME is really mature and all it took for me was "slime-connect", so it seems to be simple enough to setup

Of course on the bad side we have that it's Emacs specific hence the musing about a TernJS like backend that does the evaluation, completion etc.

My vision is to build a general purpose PHP completion/evaluation/doc/inspection tool that can be used in IDEs and so on. I think it's about time that we have something open source that can compete with the IDEs and takes it to another dynamic level.

I would like to build on components that already exist as much as possible. Currently I'm trying to use Xdebug for the evaluation of code and it could be all that is needed on that side for now. For the completion and introspection CodeSniffer seems to have nice components.

Would you be interested to build such a library?

I think the protocol and all of that can be figured out later. At first we can just use SLIME as I have the most important parts already working so that building the backend would be possible using that.

My holidays end tomorrow so I will not have so much time anymore, but I see this as a long term project with many things to ponder and learn...

**Comment by steckerhalter** [comment]
Oh, and because of Boris... d11wtq has written that he is "in the process of transitioning away from PHP to Ruby" and to me it looks as he does not invest as much time into Boris as would be needed to make it what we would like it to be. And of course the lack of Windows support does not really allow for a bigger vision anyway.
